add calculator
Tototyr/calculator pull request #1
Opened 2023-04-04 04:54 UTC by Tototyr

2023-04-04 06:13 UTC, dudeinhoodie commented
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/16040008/229703385-f368e1a8-e7c3-42d7-a514-1e64e1dd75eb.png">

классическая ошибка, нет проверки на 0

2023-04-04 06:28 UTC, dudeinhoodie requested changes
<img width="429" alt="image" src="https://user-images.githubusercontent.com/16040008/229706638-2c2cff6e-72fe-46dc-90ee-562e73ca421c.png">

2023-04-04 06:28 UTC, dudeinhoodie commented on index.html
> +    <title>Vite + React</title>
давай нормальный тайтл сразу писать

2023-04-04 06:28 UTC, dudeinhoodie commented on src/App.jsx
> +import { useState } from 'react';
лишний импорт

2023-04-04 06:28 UTC, dudeinhoodie commented on src/App.jsx
> +        <div className="App">
лишний клас, тк нет стиля для него

2023-04-04 06:28 UTC, dudeinhoodie commented on src/App.jsx
> +                <Layout className="layout">
лишний клас, тк нет стиля для него

2023-04-04 06:28 UTC, dudeinhoodie commented on src/App.jsx
> +                <Layout className="layout">
ты не учитываешь className который прокидываешь в `Layout`, оставлю коммент в самом `Layout`

2023-04-04 06:28 UTC, dudeinhoodie commented on src/providers/ThemeProvide.jsx
> +    const value = { isLight, setisLight };
смотри, строго говоря нам не важно какую именно тему мы задаим, так что можем написапть просто `toggleTheme` тк их у нас всего 2

плюс смотри, мы пишем глагом is, are, should и тд в названиях переменных только в тех случаях, когда переменные булевы, в остальных случаях не приянтно писать глагол

поэтому в данном случае было бы правильно написать `setLightTheme` но как я уже сказал лучше сделать `toggleTheme` тк у нас их всего 2

2023-04-04 06:28 UTC, dudeinhoodie commented on src/providers/ThemeProvide.jsx
> +    const value = { isLight, setisLight };
тогда по месту применения мы сможем избаиваться от


```
const toggleTheme = () => {
        setisLight(!isLight);
    };
```

2023-04-04 06:28 UTC, dudeinhoodie commented on src/index.css
> +.layout.light .button:hover{
задание под зведочкной, если будет желание, то сделай отдельный пул реквест с использованием css переменных

тогда хук `useTheme` будет просто добавлять класс к body, а сама тема разруливаться на уровне стилей
если будет желание

2023-04-04 06:28 UTC, dudeinhoodie commented on src/components/layout/Layout.jsx
> +            })}
ты в комопненте выше прокидываешь в `Layout` `className` но не учитываешь это тут
норм практика если это общий комонента делать пропс с className и закидывать его в `cn`

2023-04-04 06:28 UTC, dudeinhoodie commented on src/components/layout/Layout.jsx
> +            })}
будет примерно так 


```
className={cx('layout', className)}
```

2023-04-04 06:28 UTC, dudeinhoodie commented on src/components/hooks/useTheme.jsx
> +};
я если юзаю контекст, то держу хук с использованием всегда рядом с самим контекстом, так проще и удобнее, но это вкусовщина

2023-04-04 06:28 UTC, dudeinhoodie commented on src/components/calculator/Calculator.jsx
> +            <button className="button text-2xl" onClick={() => handleNumberClick(3)}>
Илья я же говорил что делать функции в рендере плохая история, не делай 

```onClick={() => ...}>``` это очень плохо

2023-04-04 06:28 UTC, dudeinhoodie commented on src/components/calculator/Calculator.jsx
> +            <button className="button text-2xl" onClick={() => handleNumberClick(3)}>
плохо потому что на кадлый рендер у тебя будет созаваться новая функция, а это память, ее хоть и много в бразуере, но все равно плохо так делать, потенциально проблемное место
выноси в хендлер

2023-04-04 06:28 UTC, dudeinhoodie commented on src/components/calculator/Calculator.jsx
> +    const { isLight, setisLight } = useTheme();
давай мы уберем прям из самого калькуятора смену тему, тк это не его зона ответсветнности
смотри, важно понимать что одна сущность отвечает за одну вещи, калькулятор – за калькуляции, смена темы – за смену темы и тд
щас ты смешал калькулятор и тему в одно, что плохо, давай вынесем

2023-04-04 06:28 UTC, dudeinhoodie commented on src/components/calculator/Calculator.jsx
> +    const { isLight, setisLight } = useTheme();
вероятно изменится дизайн, но это ничего

2023-04-04 06:28 UTC, dudeinhoodie commented on src/components/calculator/Calculator.jsx
> +    const { isLight, setisLight } = useTheme();
в реальной жизни конечно дизайн не надо менять самому, а только через дизайнера

2023-04-04 06:30 UTC, dudeinhoodie commented
<img width="200" alt="image" src="https://user-images.githubusercontent.com/16040008/229706786-4f1988f8-55e6-4dbc-a4c9-31bbbb77be24.png">

а зачем такая возможность?
так происходит потому что ты держишь числа как строку, кажется что можно сразу работать с числами и тогда не будет такой возможности

2023-04-06 00:19 UTC, Tototyr commented on src/index.css
> +.layout.light .button:hover{
переменные по типу цвета  ?

2023-04-06 00:20 UTC, Tototyr commented on src/components/calculator/Calculator.jsx
> +            <button className="button text-2xl" onClick={() => handleNumberClick(3)}>
я чет не допер как по нормальному сделать,  через обработку событий ?

2023-04-06 07:57 UTC, dudeinhoodie commented on src/index.css
> +.layout.light .button:hover{
да

2023-04-06 08:24 UTC, dudeinhoodie commented on src/components/calculator/Calculator.jsx
> +            <button className="button text-2xl" onClick={() => handleNumberClick(3)}>
тебе надо сделать компонент с кнопкой, который будет принимать `onClick, value, className` параметры и оттуда уже передавать цифру

2023-04-06 08:24 UTC, dudeinhoodie commented on src/components/calculator/Calculator.jsx
> +            <button className="button text-2xl" onClick={() => handleNumberClick(3)}>
пиши в личку если не понял, покажу как сделать

2023-04-06 08:26 UTC, dudeinhoodie requested changes

2023-04-06 08:26 UTC, dudeinhoodie commented on src/App.jsx
> +        <div>
а зачем тут пустой див?

2023-04-06 08:26 UTC, dudeinhoodie commented on src/providers/ThemeProvide.jsx
> +    const value = { isLight, toggleTheme };
давай в хук?

2023-04-06 08:26 UTC, dudeinhoodie commented on src/components/hooks/useTheme.jsx
го рядом с контекстом будем держать?

2023-04-07 05:26 UTC, dudeinhoodie requested changes
Уже почти все хорошо, давай дожмем компонент с кнопкой! 👍

2023-04-07 05:26 UTC, dudeinhoodie commented on src/components/buttons/Button.jsx
> +}
почему дефолтный экспорт опять?? сколько можно повторять блин


не называй компонент `Button` это слишком общее название, то есть такое название может быть, но если ты кастомишь прям кнопку и хочешь потом ее юзать во всем приложении вместо обычной кнопки, например когда делаешь ui kit/дизайн систему

давай назовем как-нибудь с привязкой к калькуяции, но мы знаем, что в самой кнопке может быть не только цифра, но и запятая и символы с деление/уможение/etc

Пускай это будет Action к примеру, но так себе название конечно, не приходит в голову лучше пока

2023-04-07 05:26 UTC, dudeinhoodie commented on src/components/buttons/Button.jsx
> +}
`onClick={() => onClick(value)}` Иля ты издеваешься? Я даже не буду писать что здесь неправильно, думай сам, я уже раз 10 уже примерно говорил про это)

2023-04-07 05:26 UTC, dudeinhoodie commented on src/components/buttons/Button.jsx
> +}
немного смущает, что мы используем проп `value` для передачи из компонента, но в самом компоненте юзаем `children`

к тому же не совсем понятно зачем нам к примеру в onClick возврвщать символы уможения, вычитания, деления и тд

давай оставим проп onClick, но value не будем передавать, если это символ мат. операции, а внутри сделаем проверку на наличие `value` при `onCLick`

то есть передаем значение по клику когда это цифра
не передаем значнеие по клику, но делаем клик, когда это мат. операция

2023-04-07 05:26 UTC, dudeinhoodie commented on src/components/buttons/Button.jsx
> +}
инкапуслируй стили для кнопки внутри кнопки, не держи их снаружи
снаружи мы только управляем позиционированием кнопки, все стили с цветами, скруглениями и так далее хранятся внутри самой кнопки

2023-04-07 05:26 UTC, dudeinhoodie commented on src/components/calculator/Calculator.jsx
> +            <Button className="button text-2xl" onClick={handleNumberClick} value={'0'}>
а почему `value` как строка?

2023-04-07 05:26 UTC, dudeinhoodie commented on src/index.css
> +}
👍

2023-04-07 12:47 UTC, Tototyr commented on src/components/calculator/Calculator.jsx
> +            <Button className="button text-2xl" onClick={handleNumberClick} value={'0'}>
я тут ошибся, не нужна там строка

2023-04-08 10:55 UTC, dudeinhoodie reviewed
поставь себе какой-нибудь github descktop чтобы мониторить дифф перед сдачей на ревью

и сам пул реквест смотри прежде чем отправлять, как минимум лишние строки и все такое ты можешь сам отловить

2023-04-08 10:55 UTC, dudeinhoodie commented on src/components/buttons/Action.css
> +
отступ лишний

2023-04-08 10:55 UTC, dudeinhoodie commented on src/components/calculator/Calculator.jsx
>                  value={'+'}
смотри, у тебя где-то `value={'+'}` а где-то `value="*"` пиши единообразный код, либо так, либо так

2023-04-08 10:55 UTC, dudeinhoodie commented on src/components/buttons/Action.jsx
> +    };
смотри, у тебя value не всегда есть, нужно добавить проверку, что он есть и только тогда передавать его, так у тебя сейчас undefined улатает для del например

2023-04-08 10:55 UTC, dudeinhoodie commented on src/components/hooks/useCalculator.jsx
> +            setResult(result.slice(0, -13));
не понял че за прикол с 13?))

использовать "магические числа" (погугли) нельзя просто так, через неделю ты не поймешь че это за 13 и откуда взялось и почему именно так, выноси в константу

константы всегда капсом и андерскором обозначаются типа `MARKET_CHANGE_OFFER_VALUE = 13`

2023-04-08 21:41 UTC, Tototyr commented on src/components/hooks/useCalculator.jsx
> +            setResult(result.slice(0, -13));
да я это что то проверял и поставил 13, должно 1 
про числа гляну

2023-04-09 04:28 UTC, dudeinhoodie requested changes

2023-04-09 04:28 UTC, dudeinhoodie commented on src/App.jsx
> +function App({ className }) {
App это рут компонент, в него { className } ты никак не сможешь передать, у него вообще пропсов не должно быть, удаляй

2023-04-09 04:28 UTC, dudeinhoodie commented on src/components/calculator/Calculator.css
> +    color: #fff;
если ты все вынес в переменные, то зачем оставил тут hex?

2023-04-09 04:28 UTC, dudeinhoodie commented on src/components/calculator/Calculator.css
> +    color: #fff;
замени на переменную тоже

2023-04-09 04:28 UTC, dudeinhoodie commented on src/components/calculator/Calculator.css
> +    color: #fff;
тоже самое

2023-04-09 04:28 UTC, dudeinhoodie commented on src/index.css
> +    color: #000000;
в css перменные

2023-04-09 04:28 UTC, dudeinhoodie commented on src/components/buttons/Action.jsx
> +        if (value !== undefined) {
тут можно проще, просто if (value)

2023-04-09 04:28 UTC, dudeinhoodie commented on src/components/buttons/Action.jsx
> +        if (value !== undefined) {
ну это на будующее

2023-04-09 04:28 UTC, dudeinhoodie commented on src/components/calculator/Calculator.jsx
> +                        {calculation.previousValue} {calculation.operation}{' '}
ой вот так лучше не делать, ужасно бесит пробелы в jsx в таком виде

давай сделаем функцию `getHistory()` которая будет принимать значение и операцию, а затем превращать это в строку

сделать это можно разными способами, через литералы или например вот так

`[value, opearation].join(' ')`

2023-04-09 04:28 UTC, dudeinhoodie commented on src/components/calculator/Calculator.jsx
> +                        {calculation.previousValue} {calculation.operation}{' '}
мне вариант с джойном нравится больше, но ты выбери какой тебе по душе

2023-04-09 04:28 UTC, dudeinhoodie commented on src/components/calculator/Calculator.jsx
> +                        {calculation.previousValue} {calculation.operation}{' '}
ну и соотственно тут ее и вывозем

2023-04-09 04:28 UTC, dudeinhoodie commented on src/components/hooks/useCalculator.jsx
> +            setResult(result.slice(0, -1));
-1 это что? давай в константу, как я писал в прошлый раз
использовать магические числа плохая практика

вот читай https://ru.hexlet.io/blog/posts/magic-numbers

2023-04-10 09:50 UTC, merged